server:
  port: ${PORT:0}

spring:
  application:
    name: account-srv
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  devtools:
    restart:
      enabled: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8010/eureka

management:
  endpoints:
    web:
      exposure:
        include: "health,info"